version: '2'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - '54432:5432'
    environment:
      POSTGRES_DB: nest-auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
